name: Deploy-IaC-TF
on:
  workflow_dispatch: # Run manually 
  push:
    branches:
    - master
    - poc-test-backendtf
    paths:
      - "deploy/terraform/**"

env:
  APP_NAME: IaC-TF
  ENV_NAME: "poc"
  AZURE_RG_LOCATION: centralus
  TF_STORAGE_RG: "poc-shared-tfstate"
  TF_STORAGE_ACCT: "poceusastfstate"
    
jobs:
  deploy-Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
    - uses: actions/checkout@v2

      # Deploy Infrastructure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    # Replace Tokens #{ENV_NAME}#: Set TF State Key = Branch name, #{SHORT_SHA}# for tags
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: '["**/*.tf"]' 

    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init -var-file ./params.bnk.tfvars -backend-config="${{env.ENV_NAME}}.backend.tfvars"

    - name: TF Apply
      run: terraform apply -auto-approve -var-file ./params.bnk.tfvars

