name: pr-deploy-IaC
on:
  workflow_dispatch: # Run manually 
  pull_request:

env:
  APP_NAME: IaC-TF
  AZURE_RG_LOCATION: centralus
  TF_STORAGE_RG: "poc-shared-tfstate"
  TF_STORAGE_ACCT: "poceusastfstate"
  PR_NUMBER: ${{ github.event.number }}
  ENV_NAME: pr${{ github.event.number }}
    
jobs:
  PR-Opened:
    if: contains (github.event.pull_reqest.action, 'opened')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
    - uses: actions/checkout@v2

    # Replace Tokens #{ENV_NAME}#: Set TF State Key = Branch name, #{SHORT_SHA}# for tags
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: '["**/*.tf", "**/*.tfvars"]' 

    # print Environment
    - name: Print Environment
      run: |
        pwd
        ls -la
        echo '*** Workflow ENV ***'
        echo 'APP_NAME:' $APP_NAME
        echo 'ENV_NAME:' $ENV_NAME
        cat backend.tf
        cat backend.actions.tfvars
        cat params.actions.tfvars

      # Deploy Infrastructure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init -var-file ./params.actions.tfvars -backend-config="backend.actions.tfvars"

    - name: TF Apply
      run: terraform apply -auto-approve -var-file ./params.actions.tfvars

  PR-Closed:
    if: contains (github.event.pull_reqest.action, 'closed')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy/terraform
    steps:
    - uses: actions/checkout@v2

    # Replace Tokens #{ENV_NAME}#: Set TF State Key = Branch name, #{SHORT_SHA}# for tags
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: '["**/*.tf", "**/*.tfvars"]' 

    # print Environment
    - name: Print Environment
      run: |
        pwd
        ls -la
        echo '*** Workflow ENV ***'
        echo 'APP_NAME:' $APP_NAME
        echo 'ENV_NAME:' $ENV_NAME
        cat backend.tf
        cat backend.actions.tfvars
        cat params.actions.tfvars

      # Deploy Infrastructure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init -var-file ./params.actions.tfvars -backend-config="backend.actions.tfvars"

    - name: TF Destroy
      run: terraform destroy -auto-approve 
